export const TASK_UPDATE = 'TASK_UPDATE';
export const TASK_UPDATE_SUCCESS = 'TASK_UPDATE_SUCCESS';
export const TASK_UPDATE_FAILURE = 'TASK_UPDATE_SUCCESS';
export const SUBTASK_UPDATE= 'SUBTASK_UPDATE';
export const SUBTASK_UPDATE_SUCCESS= 'SUBTASK_UPDATE_SUCCESS';
export const SUBTASK_UPDATE_FAILURE= 'SUBTASK_UPDATE_FAILURE';